//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cursoMVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public int edad { get; set; }
        public string sexo { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<int> codCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
    }
}
